apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel.fullname" . }}-api-gateway
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel.fullname" . }}-auth-service
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auth-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel.fullname" . }}-alert-service
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: alert-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alert-service
