"""Tests for the hashed-lockfile verifier (audit CI-07 / Wave B4)."""

import importlib.util
from pathlib import Path

REPO_CORE = Path(__file__).resolve().parents[2]
VERIFIER_PATH = REPO_CORE / "scripts" / "verify_lockfiles.py"

_HASH = "--hash=sha256:" + "0" * 64


def _load():
    spec = importlib.util.spec_from_file_location("verify_lockfiles", VERIFIER_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _service(tmp_path: Path, txt: str, lock: str) -> Path:
    svc = tmp_path / "sentinel-core" / "backend" / "svc"
    svc.mkdir(parents=True)
    (svc / "requirements.txt").write_text(txt)
    (svc / "requirements.lock").write_text(lock)
    return svc / "requirements.lock"


def test_normalize_pep503():
    v = _load()
    assert v.normalize("Flask-CORS") == "flask-cors"
    assert v.normalize("psycopg2_binary") == "psycopg2-binary"
    assert v.normalize("opentelemetry.api") == "opentelemetry-api"


def test_txt_direct_deps_strips_extras_markers_comments(tmp_path):
    v = _load()
    p = tmp_path / "requirements.txt"
    p.write_text(
        "# comment\n"
        "uvicorn[standard]>=0.30.0\n"
        "redis>=5.0.1  # inline\n"
        "azure-identity>=1.15.0\n"
        "tomli; python_version < '3.11'\n"
        "-r other.txt\n"
        "\n"
    )
    assert v.parse_txt_direct_deps(p) == ["uvicorn", "redis", "azure-identity", "tomli"]


def test_good_service_passes(tmp_path):
    v = _load()
    lock = f"# autogenerated\nflask==3.1.3 \\\n    {_HASH}\nrequests==2.31.0 \\\n    {_HASH}\n"
    lock_path = _service(tmp_path, "Flask>=3.0\nrequests>=2.0\n", lock)
    assert v.verify_service(lock_path) == []


def test_missing_hash_flagged(tmp_path):
    v = _load()
    lock = "# autogenerated\nflask==3.1.3\n"
    lock_path = _service(tmp_path, "Flask>=3.0\n", lock)
    problems = v.verify_service(lock_path)
    assert any("no --hash" in p for p in problems)


def test_drifted_dep_flagged(tmp_path):
    v = _load()
    lock = f"# autogenerated\nflask==3.1.3 \\\n    {_HASH}\n"
    lock_path = _service(tmp_path, "Flask>=3.0\nrequests>=2.0\n", lock)
    problems = v.verify_service(lock_path)
    assert any("requests" in p and "absent" in p for p in problems)


def test_no_emit_package_excluded_from_coverage(tmp_path):
    v = _load()
    # torch is in the txt but excluded via the header's --no-emit-package, so its
    # absence from the lock must NOT be flagged.
    lock = (
        "# autogenerated by uv\n"
        "#    uv pip compile requirements.txt --generate-hashes --no-emit-package torch\n"
        f"numpy==2.0.0 \\\n    {_HASH}\n"
    )
    lock_path = _service(tmp_path, "torch>=2.1.0\nnumpy>=1.26.0\n", lock)
    assert v.verify_service(lock_path) == []


def test_real_backend_lockfiles_pass():
    """The committed lockfiles must satisfy the gate."""
    v = _load()
    root = REPO_CORE.parent  # repo root
    locks = sorted(root.glob(v.BACKEND_GLOB))
    assert locks, "no committed lockfiles found"
    problems = [p for lock in locks for p in v.verify_service(lock)]
    assert problems == [], "\n".join(problems)
