"""SENTINEL DRL Feed Job

Bridges the Flink anomaly stream to the DRL Engine and Policy Orchestrator,
closing the detection → response loop:

    XDP/HIDS → Kafka(sentinel-network/host-events)
      → Flink anomaly_detection_job → Kafka(sentinel-anomalies)
        → THIS JOB
          → DRL Engine  (POST /api/v1/decide)
          → Policy Orchestrator  (POST /api/v1/policies/auto-apply)
          → Kafka(sentinel-policy-decisions)  for audit

Runs in two modes:
- Flink mode: uses PyFlink Kafka connector (production)
- Development mode: polls Kafka directly with kafka-python (local/CI)
"""

import json
import logging
import os
import sys
import time
from datetime import datetime, timezone
from typing import Any, Dict, Optional

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import config  # noqa: E402

# ── Configuration ─────────────────────────────────────────────────────────────

DRL_ENGINE_URL = os.environ.get("DRL_ENGINE_URL", "http://drl-engine:5005")
POLICY_ORCHESTRATOR_URL = os.environ.get(
    "POLICY_SERVICE_URL", "http://policy-orchestrator:5004"
)
INTERNAL_SERVICE_TOKEN = os.environ.get("INTERNAL_SERVICE_TOKEN", "")

_REQUEST_TIMEOUT = int(os.environ.get("DRL_FEED_TIMEOUT", "5"))

ANOMALIES_TOPIC = "sentinel-anomalies"
DECISIONS_TOPIC = "sentinel-policy-decisions"
GROUP_ID = "sentinel-drl-feed"

# Severity → DRL action hints (used when DRL engine is unavailable)
_FALLBACK_ACTIONS = {
    "critical": "DENY",
    "high": "RATE_LIMIT",
    "medium": "MONITOR",
    "low": "MONITOR",
}


def _headers() -> Dict[str, str]:
    h = {"Content-Type": "application/json"}
    if INTERNAL_SERVICE_TOKEN:
        h["Authorization"] = f"Bearer {INTERNAL_SERVICE_TOKEN}"
    return h


def _get_drl_decision(anomaly: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """POST the anomaly to the DRL engine and return its policy decision."""
    payload = {
        "detection_id": anomaly.get("detection_id", f"anomaly-{int(time.time())}"),
        "threat_type": anomaly.get("type", "unknown"),
        "severity": anomaly.get("severity", "medium"),
        "source_ip": anomaly.get("source_ip", ""),
        "features": anomaly,
        "confidence": anomaly.get("confidence", 0.75),
        "timestamp": anomaly.get("timestamp", datetime.now(timezone.utc).isoformat()),
    }

    try:
        resp = requests.post(
            f"{DRL_ENGINE_URL}/api/v1/decide",
            json=payload,
            headers=_headers(),
            timeout=_REQUEST_TIMEOUT,
        )
        if resp.status_code == 200:
            return resp.json()
        logger.warning(
            "DRL engine returned HTTP %s for anomaly type=%s",
            resp.status_code,
            anomaly.get("type"),
        )
    except requests.exceptions.RequestException as exc:
        logger.error("DRL engine unreachable: %s", exc)

    # Fallback: derive action heuristically from severity
    severity = str(anomaly.get("severity", "medium")).lower()
    return {
        "action": _FALLBACK_ACTIONS.get(severity, "MONITOR"),
        "source": "fallback_heuristic",
        "reason": f"DRL engine unavailable; inferred from severity={severity}",
    }


def _apply_policy(anomaly: Dict[str, Any], decision: Dict[str, Any]) -> bool:
    """Ask Policy Orchestrator to apply the DRL decision as a firewall rule."""
    action = decision.get("action", "MONITOR")

    # Only push rules that require actual firewall changes.
    if action in ("MONITOR", "ALLOW"):
        logger.info("Action=%s — no firewall change required.", action)
        return True

    source_ip = anomaly.get("source_ip", "")
    if not source_ip:
        logger.info("Action=%s but no source IP — skipping policy push.", action)
        return True

    payload = {
        "name": f"auto-{action.lower()}-{source_ip}-{int(time.time())}",
        "description": (
            f"Auto-generated by DRL Feed: {action} traffic from {source_ip}"
            f" (anomaly: {anomaly.get('type', 'unknown')})"
        ),
        "action": action,
        "source": {"ip": source_ip, "cidr": "/32"},
        "protocol": "ANY",
        "priority": 50,
        "duration": _ttl_for_severity(anomaly.get("severity", "medium")),
        "auto_applied": True,
        "drl_decision": decision,
    }

    try:
        resp = requests.post(
            f"{POLICY_ORCHESTRATOR_URL}/api/v1/policies/auto-apply",
            json=payload,
            headers=_headers(),
            timeout=_REQUEST_TIMEOUT,
        )
        if resp.status_code in (200, 201):
            logger.info(
                "Policy applied: action=%s source_ip=%s policy_id=%s",
                action,
                source_ip,
                resp.json().get("policy_id", "?"),
            )
            return True
        logger.warning(
            "Policy orchestrator returned HTTP %s", resp.status_code
        )
    except requests.exceptions.RequestException as exc:
        logger.error("Policy orchestrator unreachable: %s", exc)

    return False


def _ttl_for_severity(severity: str) -> int:
    """Return auto-block TTL in seconds based on severity."""
    return {"critical": 3600, "high": 1800, "medium": 900, "low": 300}.get(
        severity.lower(), 900
    )


def process_anomaly(anomaly: Dict[str, Any]) -> None:
    """Full pipeline: anomaly → DRL decision → policy application."""
    anomaly_type = anomaly.get("type", "unknown")
    severity = anomaly.get("severity", "medium")

    logger.info("Processing anomaly: type=%s severity=%s", anomaly_type, severity)

    decision = _get_drl_decision(anomaly)
    if decision:
        logger.info(
            "DRL decision: action=%s source=%s",
            decision.get("action"),
            decision.get("source", "drl-engine"),
        )
        _apply_policy(anomaly, decision)


# ── Flink mode ────────────────────────────────────────────────────────────────

class DRLFeedJob:
    """PyFlink streaming job: sentinel-anomalies → DRL Engine → Policy Orchestrator."""

    def setup_environment(self):
        try:
            from pyflink.datastream import StreamExecutionEnvironment
            from pyflink.table import StreamTableEnvironment, EnvironmentSettings

            self.env = StreamExecutionEnvironment.get_execution_environment()
            self.env.set_parallelism(config.parallelism)
            self.env.enable_checkpointing(config.checkpoint_interval_ms)

            settings = EnvironmentSettings.new_instance().in_streaming_mode().build()
            self.t_env = StreamTableEnvironment.create(
                self.env, environment_settings=settings
            )
            logger.info("Flink environment initialised for DRL Feed job")
            return True
        except ImportError as exc:
            logger.warning("PyFlink not available (%s) — falling back to dev mode", exc)
            self.env = None
            self.t_env = None
            return False

    def run(self):
        logger.info("Starting SENTINEL DRL Feed Job")
        if not self.setup_environment() or self.env is None:
            self._run_development_mode()
            return

        bootstrap = config.kafka.bootstrap_servers

        source_ddl = f"""
        CREATE TABLE anomalies_source (
            anomaly_type STRING,
            severity     STRING,
            source_ip    STRING,
            description  STRING,
            details      STRING,
            detected_at  STRING,
            `type`       STRING,
            confidence   DOUBLE
        ) WITH (
            'connector'                       = 'kafka',
            'topic'                           = '{ANOMALIES_TOPIC}',
            'properties.bootstrap.servers'    = '{bootstrap}',
            'properties.group.id'             = '{GROUP_ID}',
            'scan.startup.mode'               = 'latest-offset',
            'format'                          = 'json',
            'json.fail-on-missing-field'      = 'false'
        )
        """
        self.t_env.execute_sql(source_ddl)

        # For Flink mode we use a DataStream map to call the HTTP endpoints.
        # The Table API is used for source; convert to DataStream for side-effects.
        from pyflink.datastream.functions import MapFunction
        from pyflink.table import DataTypes

        class DRLProcessFunction(MapFunction):
            def map(self, row):
                try:
                    anomaly = {
                        "type": row[0],
                        "severity": row[1],
                        "source_ip": row[2],
                        "description": row[3],
                        "detected_at": row[5],
                    }
                    process_anomaly(anomaly)
                except Exception as exc:  # noqa: BLE001
                    logger.error("Error processing row: %s", exc)
                return row

        table = self.t_env.from_path("anomalies_source")
        ds = self.t_env.to_data_stream(table)
        ds.map(DRLProcessFunction())

        self.env.execute("SENTINEL DRL Feed Job")

    def _run_development_mode(self):
        """Poll Kafka directly using kafka-python (no Flink required)."""
        try:
            from kafka import KafkaConsumer
        except ImportError:
            logger.error(
                "kafka-python not installed and PyFlink unavailable — "
                "cannot start DRL feed job."
            )
            return

        bootstrap = config.kafka.bootstrap_servers
        logger.info(
            "Development mode: consuming %s from %s", ANOMALIES_TOPIC, bootstrap
        )

        consumer = KafkaConsumer(
            ANOMALIES_TOPIC,
            bootstrap_servers=bootstrap,
            group_id=GROUP_ID,
            auto_offset_reset="latest",
            enable_auto_commit=True,
            value_deserializer=lambda b: json.loads(b.decode("utf-8")),
            consumer_timeout_ms=60_000,
        )

        try:
            for message in consumer:
                try:
                    anomaly = message.value
                    process_anomaly(anomaly)
                except Exception as exc:  # noqa: BLE001
                    logger.error("Error processing Kafka message: %s", exc)
        finally:
            consumer.close()


def main():
    job = DRLFeedJob()
    job.run()


if __name__ == "__main__":
    main()
